name: Build Docker Image (nginx)

on:
  push:
    branches:
      - main
    paths:
      - "nginx"
      - ".github/workflows/docker-build-nginx.yml"
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login DockerHub
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: |
          cd nginx
          ./build.sh

      - name: Push docker image
        run: docker push -a ${{ secrets.DOCKER_USERNAME }}/nginx
